import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Question.java
 *
 * Created on Jun 10, 2019, 1:20:32 AM
 */

/**
 *
 * @author vinay
 */
public class Question extends javax.swing.JFrame {
 private PreparedStatement pst;
    /** Creates new form Question */
    public Question() {
        initComponents();
    }
public ImageIcon ResizeImg(String ImagePath)
{ImageIcon myImage =new ImageIcon(ImagePath);
Image img= myImage.getImage();
Image img2=img.getScaledInstance(T3.getWidth(), T3.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(img2);
return image;}

private Icon ResizeImage(String ImagePath) {
    ImageIcon myImage = new ImageIcon(ImagePath);
Image img= myImage.getImage();
Image img2=img.getScaledInstance(T3.getWidth(), T3.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(img2);
return image;}
void PhyQuestion(){
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
Statement stmt=con.createStatement();
String sql="Select * from PHYSICS where QNO="+T1.getText()+";";
ResultSet rs=stmt.executeQuery(sql);
while(rs.next()){
T2.setText(rs.getString("QUESTION"));
T4.setText(rs.getString("OP1"));
T5.setText(rs.getString("OP2"));
T6.setText(rs.getString("OP3"));
T7.setText(rs.getString("OP4"));
byte[]imagedata=rs.getBytes("IMG");
ImageIcon img=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(T3.getWidth(),T3.getHeight(),Image.SCALE_SMOOTH));
T3.setIcon(img);
}}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}}

void ChemQuestion(){
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
Statement stmt=con.createStatement();
String sql="Select * from Chemistry where QNO="+T1.getText()+";";
ResultSet rs=stmt.executeQuery(sql);
while(rs.next()){
T2.setText(rs.getString("QUESTION"));
T4.setText(rs.getString("OP1"));
T5.setText(rs.getString("OP2"));
T6.setText(rs.getString("OP3"));
T7.setText(rs.getString("OP4"));
byte[]imagedata=rs.getBytes("IMG");
ImageIcon img=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(T3.getWidth(),T3.getHeight(),Image.SCALE_SMOOTH));
T3.setIcon(img);
}}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}}

void MathsQuestion(){
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
Statement stmt=con.createStatement();
String sql="Select * from Maths where QNO="+T1.getText()+";";
ResultSet rs=stmt.executeQuery(sql);
while(rs.next()){
T2.setText(rs.getString("QUESTION"));
T4.setText(rs.getString("OP1"));
T5.setText(rs.getString("OP2"));
T6.setText(rs.getString("OP3"));
T7.setText(rs.getString("OP4"));
byte[]imagedata=rs.getBytes("IMG");
ImageIcon img=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(T3.getWidth(),T3.getHeight(),Image.SCALE_SMOOTH));
T3.setIcon(img);
}}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        C1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        T2 = new javax.swing.JTextArea();
        T3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("<html><u>All India Entrance Test(AIET) Prem(2019)</u></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(697, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update.png"))); // NOI18N
        jLabel2.setText("<html><u>Question Here</u></html>");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("<html><u>Select Subject</u></html>");

        C1.setFont(new java.awt.Font("Tahoma", 1, 14));
        C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Physics", "Chemistry", "Mathematics" }));

        T2.setColumns(20);
        T2.setFont(new java.awt.Font("Monospaced", 1, 13));
        T2.setRows(5);
        jScrollPane1.setViewportView(T2);

        T3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Upload.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        T6.setFont(new java.awt.Font("Tahoma", 1, 11));

        T7.setFont(new java.awt.Font("Tahoma", 1, 11));

        T4.setFont(new java.awt.Font("Tahoma", 1, 11));

        T5.setFont(new java.awt.Font("Tahoma", 1, 11));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setText("CHOOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Q.No");

        T1.setFont(new java.awt.Font("Tahoma", 1, 11));

        jRadioButton1.setText("A");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("B");

        jRadioButton3.setText("C");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("D");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("View");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(861, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T5)
                    .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T6, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T7, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(524, 524, 524))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(59, 59, 59)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4))
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JFileChooser file =new JFileChooser();
file.setCurrentDirectory(new File(System.getProperty("user.home")));
FileNameExtensionFilter filter= new FileNameExtensionFilter("*.images","jpg","png");
file.addChoosableFileFilter(filter);
int result=file.showSaveDialog(null);
if(result==JFileChooser.APPROVE_OPTION){
File selectedFile=file.getSelectedFile();
path=selectedFile.getAbsolutePath();
T3.setIcon(ResizeImage(path));
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/Library","root","manohar");
File image=new File(path);
FileInputStream fis=new  FileInputStream(image);
ByteArrayOutputStream bos=new ByteArrayOutputStream();
byte[] buf=new byte[1024];
for(int readNum; (readNum=fis.read(buf))!=-1;){
bos.write(buf,0,readNum);}
item=bos.toByteArray();} catch(Exception e){
JOptionPane.showMessageDialog(null,e.getMessage());}} 
else{JOptionPane.showMessageDialog(null,"No file Selected");}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int sub=C1.getSelectedIndex();
switch(sub){
case 0 :
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
String sql="Insert into Physics(QNO,QUESTION,OP1,OP2,OP3,OP4,IMG) VALUES(?,?,?,?,?,?,?)";
pst=con.prepareStatement(sql);
pst.setString(1, T1.getText());
pst.setString(2, T2.getText());
pst.setString(3, T4.getText());
pst.setString(4, T5.getText());
pst.setString(5, T6.getText());
pst.setString(6, T7.getText());
pst.setBytes(7, item);
pst.execute();
JOptionPane.showMessageDialog(null,"Question Added");
}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}
break;
case 1:
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
String sql="Insert into Chemistry(QNO,QUESTION,OP1,OP2,OP3,OP4,IMG) VALUES(?,?,?,?,?,?,?)";
pst=con.prepareStatement(sql);
pst.setString(1, T1.getText());
pst.setString(2, T2.getText());
pst.setString(3, T4.getText());
pst.setString(4, T5.getText());
pst.setString(5, T6.getText());
pst.setString(6, T7.getText());
pst.setBytes(7, item);
pst.execute();
JOptionPane.showMessageDialog(null,"Question Added");
}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}
break;
    default :
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
String sql="Insert into Maths(QNO,QUESTION,OP1,OP2,OP3,OP4,IMG) VALUES(?,?,?,?,?,?,?)";
pst=con.prepareStatement(sql);
pst.setString(1, T1.getText());
pst.setString(2, T2.getText());
pst.setString(3, T4.getText());
pst.setString(4, T5.getText());
pst.setString(5, T6.getText());
pst.setString(6, T7.getText());
pst.setBytes(7, item);
pst.execute();
JOptionPane.showMessageDialog(null,"Question Added");
}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}}
T1.setText("");
T2.setText("");
T4.setText("");
T5.setText("");
T6.setText("");
T7.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int sub=C1.getSelectedIndex();
switch(sub){
case 0 :
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
String sql="UPDATE PHYSICS SET QNO=?,QUESTION=?,OP1=?,OP2=?,OP3=?,OP4=?,IMG=? WHERE qno="+T1.getText()+"";
pst=con.prepareStatement(sql);
pst.setString(1, T1.getText());
pst.setString(2, T2.getText());
pst.setString(3, T4.getText());
pst.setString(4, T5.getText());
pst.setString(5, T6.getText());
pst.setString(6, T7.getText());
pst.setBytes(7, item);
pst.execute();
JOptionPane.showMessageDialog(null,"Updated");}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}
break;
case 1:
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
String sql="UPDATE CHEMISTRY SET QNO=?,QUESTION=?,OP1=?,OP2=?,OP3=?,OP4=?,IMG=? WHERE qno="+T1.getText()+"";
pst=con.prepareStatement(sql);
pst.setString(1, T1.getText());
pst.setString(2, T2.getText());
pst.setString(3, T4.getText());
pst.setString(4, T5.getText());
pst.setString(5, T6.getText());
pst.setString(6, T7.getText());
pst.setBytes(7, item);
pst.execute();
JOptionPane.showMessageDialog(null,"Updated");}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}
break;
    default :
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://" +
"localhost:3306/ON9EXAM","root","manohar");
String sql="UPDATE MATHS SET QNO=?,QUESTION=?,OP1=?,OP2=?,OP3=?,OP4=?,IMG=? WHERE qno="+T1.getText()+"";
pst=con.prepareStatement(sql);
pst.setString(1, T1.getText());
pst.setString(2, T2.getText());
pst.setString(3, T4.getText());
pst.setString(4, T5.getText());
pst.setString(5, T6.getText());
pst.setString(6, T7.getText());
pst.setBytes(7, item);
pst.execute();
JOptionPane.showMessageDialog(null,"Updated");}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int sub=C1.getSelectedIndex();
switch(sub){
    case 0:PhyQuestion();break;
    case 1:ChemQuestion();break;
    default:MathsQuestion();}// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox C1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextArea T2;
    private javax.swing.JLabel T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
String path=null;
byte[] item=null;
}
